# -*- coding: utf-8 -*-
"""Pokemon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L8QmzuIkTElSjTHuqT7Ug-bQ1-OGvk5W
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset from Google Drive
file_path = '/content/drive/My Drive/pokemons.csv'
pokemon_df = pd.read_csv(file_path)

# 1. Distribution of Pokémon by Primary Type
plt.figure(figsize=(10, 6))
sns.countplot(x='type1', data=pokemon_df, order=pokemon_df['type1'].value_counts().index)
plt.title('Distribution of Pokémon by Primary Type')
plt.xlabel('Primary Type')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 2. Correlation between Attack and Defense by Generation
plt.figure(figsize=(10, 6))
sns.scatterplot(x='atk', y='def', hue='generation', data=pokemon_df, palette='Set2')
plt.title('Correlation between Attack and Defense by Generation')
plt.xlabel('Attack')
plt.ylabel('Defense')
plt.tight_layout()
plt.show()

# 3. Pokémon Total Stats by Weight
plt.figure(figsize=(10, 6))
sns.scatterplot(x='weight', y='total', hue='generation', data=pokemon_df, palette='coolwarm', alpha=0.6)
plt.title('Pokémon Total Stats by Weight')
plt.xlabel('Weight')
plt.ylabel('Total Stats')
plt.tight_layout()
plt.show()

# 4. Speed Distribution across Generations
plt.figure(figsize=(10, 6))
sns.boxplot(x='generation', y='speed', data=pokemon_df)
plt.title('Speed Distribution by Generation')
plt.xlabel('Generation')
plt.ylabel('Speed')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 5. Evolution of Pokémon's Special Attack Over Generations
plt.figure(figsize=(10, 6))
sns.lineplot(x='generation', y='spatk', data=pokemon_df, ci=None, marker='o', color='b')
plt.title("Average Special Attack by Generation")
plt.xlabel('Generation')
plt.ylabel('Average Special Attack')
plt.grid(True)
plt.tight_layout()
plt.show()